### ISSUE TITLE
allow Usage in PHP8

### ISSUE THREAD

**Issue by boredom2** [bitmovin/bitmovin-api-sdk-php#1]
Currently, the Package is restricted to use in Environments with ^7.1, so it is not installable under PHP8. Can you please update the supported Versions to PHP8? Thanks!

**Comment by boredom2** [comment]
Any Update on this?

**Comment by boredom2** [comment]
I dont wanna stress you here - but Bitmovin is now the only Composer Reference on our System, that is not installable under PHP8. In the meantime, you released a couply of Updates already, but non of those seems to take this into Consideration.
Is there any change you add Support for PHP8 anytime soon?

**Comment by vbasky** [comment]
Any updates on this ?

**Comment by seburgi** [comment]
Thanks for reporting, we will take care of this and should have a fix ready soon.

**Comment by seburgi** [comment]
@boredom2 can you please check if our API SDK is now installable with PHP 8?

**Comment by boredom2** [comment]
@seburgi i can confirm that, thank you.

**Comment by dweinber** [comment]
Thanks everyone, closing as resolved.
